require("dotenv").config();
const express=require("express");
const cors=require("cors");
const helmet=require("helmet");
const compression=require("compression");
const rateLimit=require("express-rate-limit");
const {Pool}=require("pg");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const path=require("path");

const app=express();
const PORT=process.env.PORT||3000;
const DATABASE_URL=process.env.DATABASE_URL;
const JWT_SECRET=process.env.JWT_SECRET;
if(!DATABASE_URL||!JWT_SECRET) throw new Error("DATABASE_URL and JWT_SECRET required");
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.DB_SSL==="true"?{rejectUnauthorized:false}:false});
app.use(helmet({contentSecurityPolicy:false}));
app.use(compression());
app.use(cors({origin:process.env.ALLOWED_ORIGIN?process.env.ALLOWED_ORIGIN.split(","):true}));
app.use(express.json({limit:"1mb"}));
app.use(rateLimit({windowMs:15*60*1000,max:300}));
app.use(express.static(path.join(__dirname,"public")));
async function q(t,p=[]){return pool.query(t,p)}
function auth(req,res,next){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"Login required"});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:"Invalid token"})}}
function admin(req,res,next){if(!["admin","staff"].includes(req.user.role))return res.status(403).json({error:"Admin access required"});next()}
async function audit(req,action,entity_type,entity_id,metadata={}){try{await q("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata,ip_address) VALUES($1,$2,$3,$4,$5,$6)",[req.user?.id||null,action,entity_type,String(entity_id||""),JSON.stringify(metadata),req.ip||null])}catch{}}
async function notify(user_id,title,message){try{await q("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'in_app',$2,$3)",[user_id,title,message])}catch{}}
async function logActivity(application_id,event,note){try{await q("INSERT INTO activity(application_id,event,note) VALUES($1,$2,$3)",[application_id,event,note])}catch{}}

app.post("/api/register",async(req,res)=>{const {name,mobile,email,password}=req.body||{};if(!name||!/^[0-9]{10}$/.test(mobile||"")||!password||password.length<8)return res.status(400).json({error:"Valid name, mobile and password required"});try{const hash=await bcrypt.hash(password,12);const r=await q("INSERT INTO users(name,mobile,email,password_hash) VALUES($1,$2,$3,$4) RETURNING id,name,mobile,email,role",[name,mobile,email||null,hash]);const user=r.rows[0];res.json({user,token:jwt.sign(user,JWT_SECRET,{expiresIn:"7d"})})}catch(e){if(e.code==="23505")return res.status(409).json({error:"Mobile already registered"});throw e}});
app.post("/api/login",async(req,res)=>{const u=(await q("SELECT * FROM users WHERE mobile=$1",[req.body.mobile])).rows[0];if(!u||!(await bcrypt.compare(req.body.password||"",u.password_hash)))return res.status(401).json({error:"Invalid login"});const user={id:u.id,name:u.name,mobile:u.mobile,email:u.email,role:u.role};res.json({user,token:jwt.sign(user,JWT_SECRET,{expiresIn:"7d"})})});
app.get("/api/config",(req,res)=>res.json({whatsapp:process.env.WHATSAPP_NUMBER||"918918007538"}));
app.get("/api/banks",async(req,res)=>res.json((await q("SELECT * FROM banks WHERE active=true ORDER BY name")).rows));
app.get("/api/products",async(req,res)=>res.json((await q("SELECT * FROM products WHERE verification_status='verified' ORDER BY interest_rate ASC NULLS LAST")).rows));

app.get("/api/profile",auth,async(req,res)=>res.json((await q("SELECT * FROM customer_profiles WHERE user_id=$1",[req.user.id])).rows[0]||{}));
app.put("/api/profile",auth,async(req,res)=>{const d=req.body||{},complete=!!(d.city&&d.state&&d.employment_type&&Number(d.monthly_income)>0);const r=await q(`INSERT INTO customer_profiles(user_id,city,state,employment_type,employer_business_name,monthly_income,existing_emi,credit_score,profile_completed) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(user_id) DO UPDATE SET city=EXCLUDED.city,state=EXCLUDED.state,employment_type=EXCLUDED.employment_type,employer_business_name=EXCLUDED.employer_business_name,monthly_income=EXCLUDED.monthly_income,existing_emi=EXCLUDED.existing_emi,credit_score=EXCLUDED.credit_score,profile_completed=EXCLUDED.profile_completed,updated_at=NOW() RETURNING *`,[req.user.id,d.city||null,d.state||null,d.employment_type||null,d.employer_business_name||null,Number(d.monthly_income)||0,Number(d.existing_emi)||0,Number(d.credit_score)||null,complete]);res.json(r.rows[0])});

const LOAN_CHECKLISTS={home:[["kyc","KYC / Identity","document"],["income","Income proof","document"],["bank_statement","Bank statements","document"],["property","Property papers","document"],["legal_valuation","Legal & valuation readiness","task"],["bank_submission","Bank submission pack","task"]],personal:[["kyc","KYC / Identity","document"],["income","Income proof","document"],["bank_statement","Bank statements","document"],["employment","Employment proof","document"],["bank_submission","Bank submission pack","task"]],business:[["kyc","Promoter KYC","document"],["business_registration","Business registration","document"],["gst_financials","GST / Financials where applicable","document"],["bank_statement","Business bank statements","document"],["itr","ITR / income records where applicable","document"],["bank_submission","Bank submission pack","task"]],vehicle:[["kyc","KYC / Identity","document"],["income","Income proof","document"],["bank_statement","Bank statements","document"],["quotation","Vehicle quotation","document"],["bank_submission","Bank submission pack","task"]],education:[["kyc","Student/co-applicant KYC","document"],["admission","Admission/course proof","document"],["income","Co-applicant income proof","document"],["cost_sheet","Education cost sheet","document"],["bank_submission","Bank submission pack","task"]],gold:[["kyc","KYC / Identity","document"],["gold_assessment","Gold assessment readiness","task"],["bank_submission","Bank submission pack","task"]]};
async function phaseProgress(id){const a=(await q("SELECT * FROM applications WHERE id=$1",[id])).rows[0];const items=(await q("SELECT * FROM application_checklist WHERE application_id=$1",[id])).rows;let p=10,reqs=items.filter(x=>x.required),done=reqs.filter(x=>["received","verified","complete","not_applicable"].includes(x.status));if(reqs.length)p=20+Math.round(done.length/reqs.length*45);const stages={submitted_to_bank:70,bank_processing:78,approved:88,disbursement_pending:94,disbursed:100,rejected:100,closed:100};if(stages[a.status])p=Math.max(p,stages[a.status]);await q("UPDATE applications SET progress_percent=$1,updated_at=NOW() WHERE id=$2",[Math.min(100,p),id]);return Math.min(100,p)}
app.post("/api/workflow/applications",auth,async(req,res)=>{const d=req.body||{};if(!LOAN_CHECKLISTS[d.loan_type])return res.status(400).json({error:"Unsupported loan type"});const prof=(await q("SELECT profile_completed FROM customer_profiles WHERE user_id=$1",[req.user.id])).rows[0];const status=prof?.profile_completed?"documents_pending":"enquiry_received";const r=await q("INSERT INTO applications(user_id,loan_type,amount,tenure_months,purpose,status,progress_percent) VALUES($1,$2,$3,$4,$5,$6,10) RETURNING id",[req.user.id,d.loan_type,Number(d.amount)||0,Number(d.tenure_months)||0,d.purpose||"",status]);const id=r.rows[0].id;for(const [code,label,type] of LOAN_CHECKLISTS[d.loan_type])await q("INSERT INTO application_checklist(application_id,item_code,item_label,item_type) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING",[id,code,label,type]);await logActivity(id,"Workflow application created",d.loan_type);await notify(req.user.id,"Application created",`Application #${id} has been created.`);await phaseProgress(id);res.json({id})});
app.get("/api/workflow/my-applications",auth,async(req,res)=>{const apps=(await q("SELECT * FROM applications WHERE user_id=$1 ORDER BY id DESC",[req.user.id])).rows;for(const a of apps){a.checklist=(await q("SELECT * FROM application_checklist WHERE application_id=$1 ORDER BY id",[a.id])).rows;a.tasks=(await q("SELECT * FROM case_tasks WHERE application_id=$1 ORDER BY id DESC",[a.id])).rows;a.activity=(await q("SELECT event,note,created_at FROM activity WHERE application_id=$1 ORDER BY id DESC",[a.id])).rows}res.json(apps)});

async function crmActivity(actor,leadId,appId,type,note=""){try{await q("INSERT INTO crm_activities(actor_user_id,lead_id,application_id,activity_type,note) VALUES($1,$2,$3,$4,$5)",[actor||null,leadId||null,appId||null,type,note])}catch{}}
app.get("/api/crm/staff",auth,admin,async(req,res)=>res.json((await q(`SELECT u.id,u.name,u.mobile,u.role,s.designation,s.active FROM users u LEFT JOIN staff_profiles s ON s.user_id=u.id WHERE u.role IN ('admin','staff') ORDER BY u.name`)).rows));
app.get("/api/crm/callbacks",auth,admin,async(req,res)=>res.json((await q(`SELECT l.id,l.name,l.mobile,l.loan_type,l.next_callback_at,u.name assigned_name FROM leads l LEFT JOIN users u ON u.id=l.assigned_to WHERE l.next_callback_at IS NOT NULL AND l.status NOT IN ('closed','rejected') ORDER BY l.next_callback_at ASC LIMIT 100`)).rows));
app.get("/api/crm/pending-documents",auth,admin,async(req,res)=>res.json((await q(`SELECT a.id application_id,a.loan_type,a.bank_name,u.name customer_name,u.mobile,COUNT(*) FILTER(WHERE c.status='pending')::int pending_count FROM applications a LEFT JOIN users u ON u.id=a.user_id JOIN application_checklist c ON c.application_id=a.id GROUP BY a.id,u.name,u.mobile HAVING COUNT(*) FILTER(WHERE c.status='pending')>0 ORDER BY pending_count DESC,a.id DESC`)).rows));
app.get("/api/crm/dashboard",auth,admin,async(req,res)=>{const [ls,as,bs,money,callbacks,docs,staff]=await Promise.all([q("SELECT status,COUNT(*)::int count FROM leads GROUP BY status ORDER BY status"),q("SELECT status,COUNT(*)::int count FROM applications GROUP BY status ORDER BY status"),q(`SELECT COALESCE(bank_name,'Unassigned') bank,COUNT(*)::int cases,COALESCE(SUM(sanction_amount),0)::numeric sanctioned,COALESCE(SUM(disbursement_amount),0)::numeric disbursed FROM applications GROUP BY COALESCE(bank_name,'Unassigned') ORDER BY cases DESC`),q(`SELECT COUNT(*)::int applications,COALESCE(SUM(amount),0)::numeric requested,COALESCE(SUM(sanction_amount),0)::numeric sanctioned,COALESCE(SUM(disbursement_amount),0)::numeric disbursed FROM applications`),q("SELECT COUNT(*)::int count FROM leads WHERE next_callback_at::date=CURRENT_DATE AND status NOT IN ('closed','rejected')"),q(`SELECT COUNT(DISTINCT a.id)::int count FROM applications a JOIN application_checklist c ON c.application_id=a.id WHERE c.status='pending'`),q(`SELECT u.id,u.name,COUNT(DISTINCT l.id)::int leads,COUNT(DISTINCT a.id)::int applications FROM users u LEFT JOIN leads l ON l.assigned_to=u.id AND l.status NOT IN ('closed','rejected') LEFT JOIN applications a ON a.assigned_to=u.id AND a.status NOT IN ('closed','rejected','disbursed') WHERE u.role IN ('admin','staff') GROUP BY u.id,u.name ORDER BY u.name`)]);const leadsTotal=ls.rows.reduce((s,x)=>s+x.count,0);const converted=ls.rows.filter(x=>["approved","converted","closed_won"].includes(x.status)).reduce((s,x)=>s+x.count,0);res.json({kpis:{leads:leadsTotal,applications:money.rows[0].applications,callbacks_today:callbacks.rows[0].count,pending_document_cases:docs.rows[0].count,requested_amount:money.rows[0].requested,sanctioned_amount:money.rows[0].sanctioned,disbursed_amount:money.rows[0].disbursed,lead_conversion_percent:leadsTotal?Math.round(converted/leadsTotal*100):0},lead_funnel:ls.rows,application_funnel:as.rows,bank_performance:bs.rows,staff_workload:staff.rows})});
app.get("/api/crm/recent-activity",auth,admin,async(req,res)=>res.json((await q(`SELECT c.*,u.name actor_name FROM crm_activities c LEFT JOIN users u ON u.id=c.actor_user_id ORDER BY c.id DESC LIMIT 100`)).rows));

async function hasPermission(user,permission){if(user.role==="admin")return true;const r=await q("SELECT 1 FROM role_permissions WHERE role=$1 AND permission=$2",[user.role,permission]);return r.rowCount>0}
function requirePermission(permission){return async(req,res,next)=>{if(await hasPermission(req.user,permission))return next();return res.status(403).json({error:"Permission denied"})}}
async function accessibleBranchIds(userId,role){if(role==="admin")return (await q("SELECT id FROM branches WHERE active=true")).rows.map(x=>x.id);return (await q("SELECT branch_id id FROM staff_branch_access WHERE user_id=$1",[userId])).rows.map(x=>x.id)}
async function pickAssignee(branchId){const r=await q(`SELECT u.id,COUNT(l.id)::int open_leads FROM users u JOIN staff_branch_access s ON s.user_id=u.id AND s.branch_id=$1 LEFT JOIN leads l ON l.assigned_to=u.id AND l.status NOT IN ('closed','rejected') WHERE u.role='staff' GROUP BY u.id ORDER BY open_leads ASC,u.id ASC LIMIT 1`,[branchId]);return r.rows[0]?.id||null}
app.get("/api/branches",auth,requirePermission("reports.view"),async(req,res)=>{const ids=await accessibleBranchIds(req.user.id,req.user.role);if(req.user.role==="admin")return res.json((await q("SELECT * FROM branches ORDER BY name")).rows);if(!ids.length)return res.json([]);res.json((await q("SELECT * FROM branches WHERE id=ANY($1::bigint[]) ORDER BY name",[ids])).rows)});
app.post("/api/admin/branches",auth,admin,async(req,res)=>{const d=req.body||{};if(!d.name||!d.code)return res.status(400).json({error:"Name and code required"});const r=await q("INSERT INTO branches(name,code,city,state) VALUES($1,$2,$3,$4) RETURNING *",[d.name,d.code,d.city||null,d.state||null]);res.json(r.rows[0])});
app.post("/api/crm/leads/auto",auth,requirePermission("crm.assign"),async(req,res)=>{const d=req.body||{};if(!d.name||!d.mobile||!d.loan_type||!d.branch_id)return res.status(400).json({error:"Name, mobile, loan type and branch required"});const assignee=await pickAssignee(d.branch_id);const r=await q(`INSERT INTO leads(name,mobile,loan_type,amount,source,status,assigned_to,branch_id,note) VALUES($1,$2,$3,$4,$5,'new',$6,$7,$8) RETURNING *`,[d.name,d.mobile,d.loan_type,Number(d.amount)||0,d.source||"website",assignee,d.branch_id,d.note||null]);await crmActivity(req.user.id,r.rows[0].id,null,"lead_auto_assigned",String(assignee||"unassigned"));res.json(r.rows[0])});
function csvEscape(v){v=String(v??"");return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
app.get("/api/reports/leads.csv",auth,requirePermission("crm.export"),async(req,res)=>{const rows=(await q(`SELECT l.id,l.name,l.mobile,l.loan_type,l.amount,l.status,b.name branch,u.name assigned_name,l.created_at FROM leads l LEFT JOIN branches b ON b.id=l.branch_id LEFT JOIN users u ON u.id=l.assigned_to ORDER BY l.id DESC`)).rows;const cols=["id","name","mobile","loan_type","amount","status","branch","assigned_name","created_at"];const csv=[cols.join(","),...rows.map(r=>cols.map(c=>csvEscape(r[c])).join(","))].join("\n");res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="credimitra-leads.csv"');res.send("\uFEFF"+csv)});
app.get("/api/reports/applications.csv",auth,requirePermission("crm.export"),async(req,res)=>{const rows=(await q(`SELECT a.id,a.loan_type,a.amount,a.status,a.bank_name,a.sanction_amount,a.disbursement_amount,b.name branch,u.name customer,au.name assigned_name,a.created_at FROM applications a LEFT JOIN branches b ON b.id=a.branch_id LEFT JOIN users u ON u.id=a.user_id LEFT JOIN users au ON au.id=a.assigned_to ORDER BY a.id DESC`)).rows;const cols=["id","loan_type","amount","status","bank_name","sanction_amount","disbursement_amount","branch","customer","assigned_name","created_at"];const csv=[cols.join(","),...rows.map(r=>cols.map(c=>csvEscape(r[c])).join(","))].join("\n");res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="credimitra-applications.csv"');res.send("\uFEFF"+csv)});

app.get("/health",async(req,res)=>{try{await q("SELECT 1");res.json({ok:true,database:"up"})}catch{res.status(503).json({ok:false,database:"down"})}});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:"Server error"})});
app.get("*",(req,res)=>{const p=req.path==="/"?"index.html":req.path.replace(/^\/+/,"");res.sendFile(path.join(__dirname,"public",p),err=>{if(err)res.status(404).sendFile(path.join(__dirname,"public","404.html"))})});
app.listen(PORT,()=>console.log(`CrediMitra running on ${PORT}`));
